---
- hosts: SwarmMaster, SwarmSlave
  become: yes
  vars:
    host_key_checking: False
  tasks:
  - include_vars: vars/vars.yml

  - name: delete default docker_gwbridge
    docker_network:
      name: docker_gwbridge
      state: absent
      force: yes
  
  - name: create new docker_gwbridge
    docker_network:
      name: docker_gwbridge
      driver: "bridge"
      attachable: "no"
      enable_ipv6: "no"
      state: present
      ipam_config:
        - subnet: "18.7.0.0/16"
          gateway: "18.7.0.1"
      driver_options:
        com.docker.network.bridge.enable_icc: "false"
        com.docker.network.bridge.enable_ip_masquerade: "true"
        com.docker.network.bridge.name: "docker_gwbridge"


  - name: Init swarm on the first node
    docker_swarm:
      state: present
      advertise_addr: "{{ hostvars[inventory_hostname]['secondary-ip'] }}"
      tls: yes
      validate_certs: yes
    register: result
    when: inventory_hostname == groups['SwarmMaster'][0]


  - name: Get join-token for manager nodes
    set_fact:
      join_token_manager: "{{ hostvars[groups['SwarmMaster'][0]].result.swarm_facts.JoinTokens.Manager }}"

  - name: Get join-token for worker nodes
    set_fact:
      join_token_worker: "{{ hostvars[groups['SwarmMaster'][0]].result.swarm_facts.JoinTokens.Worker }}"


  - name: "debug"
    debug:
      msg: 
      - "remote adds: {{ master_ips }}"
      - "advertise add: {{ hostvars[inventory_hostname]['secondary-ip'] }}"
      - "Join token manager: {{ join_token_manager }}"
      - "Join token worker: {{ join_token_worker }}"



  - name: Join other managers
    docker_swarm:
      state: join
      join_token: "{{ join_token_manager }}"
      advertise_addr: "{{ hostvars[inventory_hostname]['secondary-ip'] }}"
      remote_addrs: "{{ master_ips }}"
    when:
      - inventory_hostname in groups['SwarmMaster']
      - inventory_hostname != groups['SwarmMaster'][0]

  - name: Join workers
    docker_swarm:
      state: join
      join_token: "{{ join_token_worker }}"
      advertise_addr: "{{ hostvars[inventory_hostname]['secondary-ip'] }}"
      remote_addrs: "{{ master_ips }}"
    when:
      - inventory_hostname not in groups['SwarmMaster']